# UNA FUNCION ES UN CONJUNTO DE INSTRUCCIONES AGRUPADAS BAJO UN NOMBRE
# EN PARTICULAR COMO UN PROGRAMA MA PEQUEÑO QUE CUMPLE UNA FUNCION ESPECIFICA.
# LA FUNCION SE PUEDE REUTILIZAR CON EL SIMPLE HECHO DE INVOCARLA ES DECIR MANDARLA LLAMAR.


sintaxis:

 def nombredeMifuncion(parametros)
 bloque o conjunto de intrucciones

  